#!/bin/env bash

picom --experimental-backend &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
clipit-applet &
openrgb --noautoconnect -m Off &
feh --bg-fill /home/renzorico/polybar-themes/wallpapers/981872.jpg &
/home/renzorico/.config/polybar/launch.sh --forest &
/home/renzorico/autohide_polybar.sh
