#!/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd &

if [[ $(xrander -q | grep 'HDMI-1-0 connected') ]]; then
  xrandr --output eDP-1 --primary --mode 1920x1080 --rotate normal --output HDMI-1-0 --mode 1280x800 --rate 59.81 --left-of eDP-1 --auto
fi

bspc monitor HDMI-1-0 -d 4 5 6
bspc monitor eDP-1 -d 1 2 3  
bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config automatic_scheme horizontal
bspc config initial_polarity first_child

bspc config normal_border_color  "#0D1117"
bspc config focused_border_color "#C9D1D9"
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^2' state=tiled follow=on
bspc rule -a discord       desktop='^7' state=tiled follow=on
bspc rule -a Steam         desktop='^8' state=tiled follow=off
bspc rule -a thunderbird   desktop='^3' state=tiled follow=on
bspc rule -a Virt-manager  desktop='^9' state=tiled follow=on

picom --config ~/.config/picom/picom.conf &
/home/renzorico/.config/bspwm/autostart &
/home/renzorico/.config/bspwm/touchpad-settings.sh &
/home/renzorico/Downloads/981872.jpg &
/home/renzorico/.config/polybar/material/scripts/pywal.sh /home/renzorico/polybar-themes/wallpapers/981872.jpg &
