[colors]
base = #1e1e2e
mantle = #181825
crust = #11111b
text = #cdd6f4
subtext0 = #a6adc8
subtext1 = #bac2de
surface0 = #313244
surface1 = #45475a
surface2 = #585b70
overlay0 = #6c7086
overlay1 = #7f849c
overlay2 = #9399b2
blue = #89b4fa
lavender = #b4befe
sapphire = #74c7ec
sky = #89dceb
teal = #94e2d5
green = #a6e3a1
yellow = #f9e2af
peach = #fab387
maroon = #eba0ac
red = #f38ba8
mauve = #cba6f7
pink = #f5c2e7
flamingo = #f2cdcd
rosewater = #f5e0dc
transparent = #FF00000

[colors]
background = ${colors.base}
background-alt = ${colors.blue}
foreground = ${colors.text}
primary = ${colors.mauve}
secondary = ${colors.mantle}
alert = ${colors.red}
disabled = ${colors.subtext1}

[bar/bar]
monitor = ${env:MONITOR:}
width = 100%
height = 36
radius = 8.0
offset-x = 0%
offset-y = 0
fixed-center = true 
border-size = 3pt
dpi = 100

background = ${colors.background}
foreground = ${colors.foreground}

bottom = false 

line-size = 6pt

border-color = #00000000

padding-left = 3
padding-right = 3

module-margin = 1

separator = |
separator-foreground = ${colors.primary}

font-0 = MesloLGS Nerd Font Mono:size=16;6

modules-left = xworkspaces xwindow
modules-center = date
modules-right = pulseaudio battery temperature gpu-temperature memory cpu bluetooth wireless-network

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.mauve}
label-active-foreground = ${colors.crust}
label-active-underline= ${colors.mauve}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:40:...%

[module/gpu-temperature]
type = custom/script
exec = ~/.config/polybar/scripts/gpu_temp.sh
interval = 3
label = GPU: %output%°C

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "VOL "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "RAM "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[module/battery]
type = internal/battery
format-prefix = "BAT "
format-prefix-foreground = ${colors.primary}

full-at = 99
format-charging = <animation-charging> <label-charging>
animation-charging-0 = 
animation-charging-1 = 
animation-charging-2 = 
animation-charging-3 = 
animation-charging-4 = 
; Framerate in milliseconds
animation-charging-framerate = 750
animation-charging-foreground = ${colors.peach}
format-discharging = <ramp-capacity> <label-discharging>
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
low-at = 5
battery = BAT1
adapter = ACAD
poll-interval = 5

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = %{F#F0C674}W:{F-} %essid%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d | %H:%M:%S

label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/alsa]
type = internal/alsa

; Soundcard to be used
; Usually in the format hw:# where # is the card number
; You can find the different card numbers in `/proc/asound/cards`
master-soundcard = default
speaker-soundcard = default
headphone-soundcard = default

; Name of the master, speaker and headphone mixers
; Use the following command to list available mixer controls:
; $ amixer scontrols | sed -nr "s/.*'([[:alnum:]]+)'.*/\1/p"
; If master, speaker or headphone-soundcard isn't the default, 
; use `amixer -c # scontrols` instead where # is the number 
; of the master, speaker or headphone soundcard respectively
;
; Default: Master
master-mixer = Master

; Optionally define speaker and headphone mixers
; Default: none
;;speaker-mixer = Speaker
; Default: none
;;headphone-mixer = Headphone
;
; NOTE: This is required if headphone_mixer is defined
; Use the following command to list available device controls
; $ amixer controls | sed -r "/CARD/\!d; s/.*=([0-9]+).*name='([^']+)'.*/printf '%3.0f: %s\n' '\1' '\2'/e" | sort
; You may also need to use `amixer -c # controls` as above for the mixer names
; Default: none
;;headphone-id = 9

; Use volume mapping (similar to amixer -M and alsamixer), where the increase in volume is linear to the ear
; Default: false
;;mapped = true

; Interval for volume increase/decrease (in percent points)
; Default: 5
interval = 5

; Available tags:
;   <label-volume> (default)
;   <ramp-volume>
;   <bar-volume>
format-volume = <ramp-volume><label-volume>
format-volume-overline = ${color.background}
format-volume-underline = ${color.background}

; Available tags:
;   <label-muted> (default)
;   <ramp-volume>
;   <bar-volume>
format-muted = <label-muted>
format-muted-prefix = 
format-muted-prefix-background = ${color.red}
format-muted-prefix-padding = 1
format-muted-overline = ${color.background}
format-muted-underline = ${color.background}

; Available tokens:
;   %percentage% (default)
label-volume = %percentage%%
label-volume-background = ${color.background-alt}
label-volume-padding = 1

; Available tokens:
;   %percentage% (default
label-muted = "Muted"
label-muted-foreground = ${color.foreground}
label-muted-background = ${color.background-alt}
label-muted-padding = 1

; Only applies if <ramp-volume> is used
ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-background = ${color.blue}
ramp-volume-padding = 1

; If defined, it will replace <ramp-volume> when
; headphones are plugged in to `headphone_control_numid`
; If undefined, <ramp-volume> will be used for both
; Only applies if <ramp-volume> is used
ramp-headphones-0 = 
ramp-headphones-background = ${color.blue}
ramp-headphones-padding = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/backlight]
;type = internal/xbacklight
type = internal/backlight

; Use the following command to list available cards:
; $ ls -1 /sys/class/backlight/
card = intel_backlight
;card = amdgpu_bl0

; Available tags:
;   <label> (default)
;   <ramp>
;   <bar>
format = <ramp><label>
format-overline = ${color.background}
format-underline = ${color.background}

; Available tokens:
;   %percentage% (default)
label = %percentage%%
label-background = ${color.background-alt}
label-padding = 1

; Only applies if <ramp> is used
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-3 = 
ramp-4 = 
ramp-background = ${color.lime}
ramp-padding = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/temperature]
type = internal/temperature
interval = 3
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon4/temp1_input
warn-temperature = 75
units = true
label = CPU: %temperature-c%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/wireless-network]
type = internal/network
interface = wlp0s20f3
interval = 3.0
unknown-as-up = true
format-connected-background = ${color.background}
format-connected-foreground = ${color.foreground}
format-connected-padding = 1
format-connected = %{A1:$HOME/rofi-network-manager/rofi-network-manager.sh:}<ramp-signal> <label-connected>%{A}
label-connected = %essid%
format-disconnected-background = ${color.background}
format-disconnected-foreground = ${color.foreground}
format-disconnected-padding = 1
format-disconnected = %{A1:$HOME/rofi-network-manager/rofi-network-manager.sh:}<label-disconnected>%{A}
label-disconnected =""
ramp-signal-0 = "󰤯"
ramp-signal-1 = "󰤟"
ramp-signal-2 = "󰤢"
ramp-signal-3 = "󰤥"
ramp-signal-4 = "󰤨"
ramp-signal-foreground = ${color.white}

[module/bluetooth]
type = custom/script
exec = /home/renzorico/.config/polybar/scripts/system-bluetooth-bluetoothctl.sh
tail = true
click-left = /home/renzorico/.config/polybar/scripts/system-bluetooth-bluetoothctl.sh --toggle &
; vim:ft=dosini
